### ISSUE TITLE
Discuss: Add ability for school owners to invite users to their schools

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#26]
# What we need

Here you go ...

## Invite Model

We'll need an `Invite` model, which will include the following params:

- school_id
- email _(of the user being invited)_
- message _(custom message --optional)_

## InviteRole Model

and an `InviteRole` model which will contain the roles the school owner wishes the grant the invited user. It will include the following params:

- invite_id _(FK reference to invites)_
- role_id _(FK reference to roles)_

## Workflow

- An invite must include at least a role
- Only an admin and school_owner can make an invite
- An admin can make an invite to any school
- A school_owner can only invite to schools he/she owns
- An invite is deleted as soon as it is accepted or rejected.

## Extras

- We might need a new role called `invite_creator` for users within a school who can invite others, but are not school owners.

**Comment by jcobhams** [comment]
What happens when an invite is accepted?

**Comment by mykeels** [comment]
If the user already exists, those roles are added to that user.

Else, the user is created with those roles.

Note that some roles have special tables e.g.

student -> students table
staff -> staff table

**Comment by mykeels** [comment]
### Description for the resolve(...) method in InviteService

It would accept an id parameter, and consider each role in the invite, then perform the following actions:

a. If ADMINISTRATOR, add an `admin` role to the user with 
```php
$user->roles()->attach([
                    $role->id => [
                        'school_id' => $school->id
                    ]
                ]);
```
b. If SCHOOL_OWNER, add a `staff` and `school-owner` role to the user, and an entry in the staff table
c. If STAFF, add a staff role to the user, and 
    - create an entry in the staff table for the user
    - check if the "extras" parameter is a JSON object with a "department_id" parameter. 
    - If "department_id" exists, update the staff entry with that department_id
d. If STUDENT, add a student role to the user, and
  - create an entry in the students table for the user, with its "program_id" obtained from the "extras" column which is a stringified JSON object.

**Comment by mykeels** [comment]
Done! Thanks, @thecodearcher
