### ISSUE TITLE
Discussion: Add Prospect model and migration

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#27]
A prospect is a potential student for any school. It's for admission applicants, who go through an approval process before they can become students. The prospect needs to have specific assets such as 

- WAEC Results
- JAMB
- Birth Certificate, etc

that a registrar can view and approve before the prospect can become a student.

## What we need

We need an abstraction model to handle these files like an `Asset` model. I'm yet to figure out how this would work. I'll update this description as I think about it. 

For now, any ideas?

**Comment by mykeels** [comment]
We can draw inspiration from these two models:

- [Image](https://github.com/college-portal/college-portal/blob/edge/app/Models/Image.php)
- [ImageType](https://github.com/college-portal/college-portal/blob/edge/app/Models/ImageType.php)

**Comment by Temidayojnr** [comment]
I'm guessing the results will be uploaded as PDFs??

**Comment by mykeels** [comment]
Yeah, we can restrict the file format for uploads. Is there a reason a student would need to upload a PDF during admissions though? 😂

**Comment by Temidayojnr** [comment]
Lol, was just thinking about it considering the fact that the WAEC result is a list of grades from different subjects.

**Comment by mykeels** [comment]
Yeah, you're right ... I'm also thinking the school might want the scores on the different WAEC subject grades for further processing later.

For now, we're sure we'll be needing this till we figure this issue out https://github.com/college-portal/college-portal/issues/28

**Comment by mykeels** [comment]
Now that #28 is done, we can discuss this even further. cc @Temidayojnr @jcobhams 

Remember [`Content` and `ContentType`](https://github.com/college-portal/college-portal/issues/17) models?

Now, a School can determine what file-assets their `Prospects` need to provide to be eligible for admission.

E.g. A school can create a `ContentType` with name as `prospect-asset`, and related `Content` with values like

- Birth Certificate
- WAEC Result
- NECO Result

In the prospect admission flow (in the UI), the prospect would have to provide all these file-assets one after the other before his/her application will be viewed by the registrar for approval.

**Comment by mykeels** [comment]
Another `ContentType` called `prospect-content` can have related content with values like

- WAEC Registration Number
- JAMB Number

Which the prospect has to also provide during the admission flow, so that the school has records for these values without us having to hard-code this flow.

**Comment by Temidayojnr** [comment]
So which part am I to work on there?

**Comment by thecodearcher** [comment]
@Temidayojnr are you working on this issue?
