### ISSUE TITLE
Support blacklisting Json Web Tokens

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#44]
There's currently no way to blacklist a particular JWT. We need this functionality if we're serious about security.

**Comment by thecodearcher** [comment]
Ok. whats the possible workflow of this?
I'm thinking we have a table where we store the blacklisted JWT and also how do we know if a JWT is to be blacklisted

**Comment by mykeels** [comment]
Actually, I'm now beginning to wonder do we really need this? @thecodearcher 😂

**Comment by thecodearcher** [comment]
Lol :smile: I don't think we need it, because the tokens expire eventually. @mykeels

**Comment by mykeels** [comment]
Okay, I'll close this till we eventually do. Thanks!
