### ISSUE TITLE
Send User a Verification Mail after Registration

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#48]
To prevent spam, 

- [x] users should verify that they own the emails they provide.
- [x] users should also be prevented from login till they have completed the registration.
- [x] It should be possible to resend such an email

![image](https://user-images.githubusercontent.com/11996508/44112896-5262f66c-9ffe-11e8-9fba-fbdbefcec613.png)

**Comment by thecodearcher** [comment]
If the mail is to be resent, how does one go about that?. I'm assuming the school owner or admins can do this from their dashboard where they see all failed mails :thinking:

**Comment by mykeels** [comment]
@thecodearcher we could make a POST request to an endpoint like `auth/verification` and include the email in the body.

If the email provided belongs to a user that has not been verified, we resend the verification mail.

**Comment by thecodearcher** [comment]
@mykeels ok, this will work. Is this ```auth/verification```  used while logging in?

If not, i think its better this is checked and mail resent at login authentication level instead of having to make a request to another endpoint :thought_balloon:

**Comment by mykeels** [comment]
A POST request to `/auth` is used when logging in.

It's better to have a separate endpoint cos we don't want to send the verification mail every time the user attempts to login.

Or, are you concerned about anyone being able to trigger resending a verification link for any user? @thecodearcher

**Comment by thecodearcher** [comment]
@mykeels  I get your point now if we send the mail when logging in we might end up sending multiple emails if the user keeps trying to login.

So when a user tries to login and he/she is not yet verified they will have to fill in their email in a different form that sends the verification code via the ```auth/verification``` endpoint :clap:

**Comment by mykeels** [comment]
Another strategy is, rather than completely fail a login for a user that has not verified their email, we could respond with 403 (forbidden), and a response body containing a token that is only useful for making a request to `auth/verification`. @thecodearcher

This would fix the issue of anyone being able to trigger sending verification mails.

**Comment by thecodearcher** [comment]
ok. that's even better
