### ISSUE TITLE
Wiki Documentation Guide

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#5]
We need a way to explain the architecture to newcomers, and this requires writing a wiki here, that we can refer people who are interested in understanding how the software works to.

- [ ] Home
- [ ] Setup and Installation
- [ ] Models
  - [ ] Asset
  - [ ] Asset Type
  - [ ] Chargeable
  - [ ] Chargeable Service
  - [ ] Content
  - [ ] Content Type
  - [ ] Course
  - [ ] Course Dependency
  - [ ] Department
  - [ ] Event
  - [ ] Faculty
  - [ ] Grade
  - [ ] Grade Type
  - [ ] Group
  - [ ] Image
  - [ ] Image Type
  - [ ] Intent
  - [ ] Intent Type
  - [ ] Invite
  - [ ] Invite Role
  - [ ] Level
  - [ ] Payable
  - [ ] Program
  - [ ] Program Credit
  - [ ] Prospect
  - [ ] Role
  - [ ] School
  - [ ] Semester
  - [ ] Semester Type
  - [ ] Session
  - [ ] Staff
  - [ ] Staff Teach Course
  - [ ] Student
  - [ ] Student Takes Course
  - [ ] User
  - [ ] User Has Role
- [ ] [Contribution](https://github.com/college-portal/college-portal/blob/edge/CONTRIBUTING.md)
  - [ ] Fixes and Enhancements
- [ ] Endpoint Design Pattern
  - [ ] Request (Form)
  - [ ] Filter
  - [ ] Controller
  - [ ] Policy
  - [ ] Service
  - [ ] Repository
- [ ] Testing

**Comment by mykeels** [comment]
## Setup 

- Clone this repository
- Checkout the edge branch. `git checkout edge`
- Be sure to have Laravel Development Environment [setup on your system](https://laravel.com/docs/5.6/installation)
- Copy the [.env.example](./.env.example) file to a .env file and update its values
- Create an App Key with `php artisan key:generate`
- Run `composer update` to install dependencies
- To use the image upload feature
  - Create a cloudinary account
  - Fill the CLOUDINARY_* fields in .env
- Create a MySQL, PostgreSQL or SQLite DB and connect it via the .env file
- Add the migrations to the DB by running `php artisan migrate`
- To seed your DB with test data, run `php artisan db:seed`
- To serve the application, run `php artisan serve`

**Comment by mykeels** [comment]
## Models

This is a description of the various models that make up the college-portal system.

### [Model 1](#/link/to/model/file)

Give its description here …

| Name	          | Data Type		| Description               |
|---------------|-----------|---------------------------|
| PROPERTY 1	| Type 1	| Description of Property 1 |
| PROPERTY 2	| Type 2	| Description of Property 2 |
| [RELATIONSHIP 1](#/link/to/relationship/model/description/hash)	| Has Many / Belongs To	| Description of Relationship 1 |

> You can get the datatypes and relationships from the model's code. See [example](https://github.com/college-portal/college-portal/blob/edge/app/Models/Asset.php) for the Asset model

### API Documentation

See API Documentation for Model 1 [here](https://college-portal.github.io/college-portal/#get-users).

**Comment by mykeels** [comment]
## Contribution

Hello, thanks for wanting to contribute. Here are a few things you should know ...

### Fixes and Enhancements

- Create an issue stating your intentions. If an issue already exists, indicate in a comment that you're interested in working on it.
- Fork this repository.
- In your fork, checkout the `edge` branch.
- Make a PR to the `edge` branch, giving a clear description that references the issue.

**Comment by mykeels** [comment]
## Endpoint Design Pattern

The code for this API's endpoints are structured in a design pattern consisting several moving parts, each important to making it work efficiently.

```
Request (Form) => Filters => Controller => Service => Repository => Database
                                   ||
                                 Policy
```

### Request (Form)

Read about [Laravel Requests](https://laravel.com/docs/5.6/requests) which handle GET, PUT, and DELETE actions in this project.

Read about [Laravel Form Requests](https://laravel.com/docs/5.6/validation#creating-form-requests) which handle POST actions in this project. It has the advantage of including authorisation and validation for such requests. 

### Filters

Filters are a construct that help manage data access and transformation with query strings in Laravel applications. Read more about them [here](https://medium.com/@mykeels/writing-clean-composable-eloquent-filters-edd242c82cc8) and [here](https://medium.com/@mykeels/writing-even-better-eloquent-filters-ee23ab24a49c).

This project primarily uses filters to control the structure of data it responds with. 

#### For Example (User with Staff)

To retrieve a user's basic profile, you would use the `~/users/:id` endpoint. 

If you wanted to retrieve all staff profiles belonging to that user along with the basic profile, you would use `~/users/:id?with_staff`.

### Controller

Read about [Laravel Controllers](https://laravel.com/docs/5.6/controllers).

### Policy

Read about [Laravel Policies](https://laravel.com/docs/5.6/authorization#creating-policies), an authorisation mechanism we have embraced for its robustness, and ease of use.

### Service

A service is a class that contains business logic used within the application. It has access to Repository classes, and makes use of their functionality to work with the database. 

Authorisation that is not captured by Policy and Form Request classes can be handled within Service classes.  See example here.

### Repository

A repository class handles data access, and typically has 6 methods

| Name	          | Arguments		| Description              |
|---------------|-----------|---------------------------|
| list	| User, Filter |  This returns a collection of data, belonging to a model, that a user has access to, and filtered by the query strings. It may go by other names like the lower-case, plural form of its model name.     |
| single	| $id, Filter	| This returns a single model instance, located by its id, and subject to query string filters. It may go by other names like the lower-case form of its model name |
| delete	| $id | This removes a model instance, located by its id from its table.     |
| create	| Array	| This creates a model instance      |
| update	| $id, Array | This modifies the attributes of an existing model instance, located by its id      |
| count	| Filter	| This returns the number of model instances matching filter queries      |

**Comment by mykeels** [comment]
Wiki done 💃

**Comment by sage-godspeed** [comment]
Yay, I wish I could have been more helpful
