### ISSUE TITLE
Student categories: Undergrad, PostGrad, Research students...

### ISSUE THREAD

**Issue by Nimisoere** [college-portal/college-portal#53]

**Comment by mykeels** [comment]
What's the difference between research students and others?

**Comment by Nimisoere** [comment]
PhD. Students. (Computer Science- Undergrad, Postgrad, PhD)

**Comment by mykeels** [comment]
The schools I know of, operate their postgrad schools as a different entity, so having a separate instance of this college-portal software for undergrads and postgrads would work for such a case.

**Comment by Nimisoere** [comment]
I see. I have seen postgrads take the same courses with undergrads. So in this case, would these courses be created for both schools?

**Comment by mykeels** [comment]
Yes @Nimisoere ... these courses, even though they have the same name, would have a different Course Code like CSC 601 instead of CSC 201.
