### ISSUE TITLE
Some schools run a Collegiate  system: has this been considered

### ISSUE THREAD

**Issue by Nimisoere** [college-portal/college-portal#54]

**Comment by mykeels** [comment]
What's a collegiate system? @Nimisoere

**Comment by Nimisoere** [comment]
Mykeels University --> Ikechi College, Michael college. From a generic point of view. How do we assign students to groups, societies or bodies

**Comment by mykeels** [comment]
The groups module is supposed to address this issue. This is still under construction, as all the kinks still have to be worked out. 

Here's the [Model class](https://github.com/college-portal/api-models/blob/master/src/Group.php) for groups.

To help work it out, what do the groups mean? Or do?

**Comment by Nimisoere** [comment]
Oh, nice. Groups are just a collection of users.
